### ISSUE TITLE
client is closed error

### ISSUE THREAD

**Issue by ozykhan** [firstbatchxyz/warp-contracts-redis#7]
Getting `client is closed error` while trying to use the latest version.

@erhant you can check the code I am getting an error [here](https://github.com/firstbatchxyz/hollowdb-crud-microservices/blob/cbbdc39f5beef04505846b0306645cb2e72e5947/get-service/src/index.ts#L21). And my redisClient and hollowdb creation process is [here](https://github.com/firstbatchxyz/hollowdb-crud-microservices/blob/cbbdc39f5beef04505846b0306645cb2e72e5947/get-service/src/clients/hollow.ts).

The error I am getting
```
/home/fco/Documents/GitHub/hollowdb-crud-microservices/get-service/node_modules/@redis/client/dist/lib/client/index.js:490
        return Promise.reject(new errors_1.ClientClosedError());
                              ^

ClientClosedError: The client is closed
    at RedisClient._RedisClient_sendCommand (/home/fco/Documents/GitHub/hollowdb-crud-microservices/get-service/node_modules/@redis/client/dist/lib/client/index.js:490:31)
    at RedisClient.commandsExecutor (/home/fco/Documents/GitHub/hollowdb-crud-microservices/get-service/node_modules/@redis/client/dist/lib/client/index.js:188:154)
    at BaseClass.<computed> [as SET] (/home/fco/Documents/GitHub/hollowdb-crud-microservices/get-service/node_modules/@redis/client/dist/lib/commander.js:8:29)
    at RedisCache.put (/home/fco/Documents/GitHub/hollowdb-crud-microservices/get-service/node_modules/warp-contracts-redis/lib/cjs/redisCache.js:277:31)
    at CacheableStateEvaluator.putInCache (/home/fco/Documents/GitHub/hollowdb-crud-microservices/get-service/node_modules/warp-contracts/lib/cjs/core/modules/impl/CacheableStateEvaluator.js:126:26)
    at CacheableStateEvaluator.onStateEvaluated (/home/fco/Documents/GitHub/hollowdb-crud-microservices/get-service/node_modules/warp-contracts/lib/cjs/core/modules/impl/CacheableStateEvaluator.js:67:20)
    at CacheableStateEvaluator.doReadState (/home/fco/Documents/GitHub/hollowdb-crud-microservices/get-service/node_modules/warp-contracts/lib/cjs/core/modules/impl/DefaultStateEvaluator.js:244:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CacheableStateEvaluator.eval (/home/fco/Documents/GitHub/hollowdb-crud-microservices/get-service/node_modules/warp-contracts/lib/cjs/core/modules/impl/CacheableStateEvaluator.js:62:16)
    at async HandlerBasedContract.readState (/home/fco/Documents/GitHub/hollowdb-crud-microservices/get-service/node_modules/warp-contracts/lib/cjs/contract/HandlerBasedContract.js:121:28)

Node.js v18.12.1
error Command failed with exit code 1.
```

**Comment by fco-fbatch** [comment]
Bonus explenation,

If I try to manually call `connect()` before the `hollowdb.readState()`, either by directly using redisClient or using the redisClient by underlying `storage()` method, I am getting the connection is already opened error. 

If I omit using `connect()` I get The client is closed error.

**Comment by fco-fbatch** [comment]
As a solution, I am offering adding a separate opt `isManaged ` when creating the RedisCache. If `isManaged ` is true then the underlying warp instance cannot close or open connections to redis only the caller can. You can check [this](https://github.com/firstbatchxyz/warp-contracts-redis/tree/fco/external-control) branch for the proposed changes. I also changed the redisClientType.

**Comment by erhant** [comment]
#8 introduces this temporary fix, along with major changes to the code. now, the client is created within the cache as is the case in LMDB.

**Comment by erhant** [comment]
@fco-fbatch the recent pull seems to fix the error, without the workaround!
still not closing this as we need further testing

**Comment by erhant** [comment]
probably should be mentioned, the other SortKeyCache implementations are targeted for local environments (as per the lazy-evaluation on client-side requirements) however Redis cache aims to provide a single online cache for multiple clients.

This may be the root cause of `open` and `close` bugs.
